version : '3'
services:
  ocean:
    build: ./php
    image: ocean_php:latest
    container_name: ocean
    hostname: "ocean"
    volumes:
      - ./src_CRUD:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - database_ocean1
  database_ocean1:
    image: mariadb:10.2
    container_name: database_ocean1
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: ocean_pemweb
      MYSQL_PASSWORD: ocean123!.
      MYSQL_ROOT_PASSWORD: ocean123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_pemweb_ocean:
    build: ./nginx
    image: nginx_pemweb_ocean:latest
    container_name: nginx_pemweb_ocean
    hostname: "nginx_pemweb_ocean"
    ports:
      - "80:80"
    volumes:
      - ./src_CRUD:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ocean